var quotes2=
[
  'Where love reigns, there is no will to power\; and where the will to power is paramount, love is lacking. The one is but the shadow of the other.',
  'Anyone who overlooks the instincts will be ambuscaded by them.',
  'So far as we know, consciousness is always ego-consciousness. in order to be conscious of myself, I must be able to distinguish myself from others. Relationship can only take place where this distinction exists.',
  'For two personalities to meet is like mixing two chemical substances: if there is any combination at all, both are transformed.'
];
var quotes3=
[
  'The elementary fact that a person always thinks another’s psychology is identical with his own effectively prevents a correct understanding of feminine psychology.',
  'Women are increasingly aware that love alone can give them full stature, just as men are beginning to divine that only the spirit can give life its highest meaning. Both seek a psychic relationship, because love needs the spirit, and the spirit love, for its completion.',
  'The psychiatrist knows only too well how each of us become the helpless but not pitiable victim of his own sentiments. Sentimentality is the superstructure erected upon brutality.',
  'Seldom or never does a marriage develop into an individual relationship smoothly and without crises. There is no birth of consciousness without pain.',
  'Nothing exerts a stronger psychic effect upon the human environment, and especially upon children, than the life which the parents have not lived.',
  'The psychic health of the adult individual, who in childhood was a mere particle revolving in a rotary system, demands that he should himself become the centre of a new system.',
  'The wine of youth does not always clear with advancing years; sometimes it grows turbid.',
  'From the middle of life onward, only he remains vitally alive who is ready to die with life.',
  'We must not forget that only a very few people are artists in life; that the art of life is th most distinguished and rarest of all the arts. Who ever succeeded in draining the whole cup with grace?',
  'The greater the tension, the greater is the potential. Great energy springs from a correspondingly great tension between opposites.',
  'Civilization does not consist in progress as such and in mindless destruction of the old values, but in developing and refining the good that has been won.',
  'The essence of culture is continuity and conservation of the past; craving for novelty produces only anti-culture and ends in barbarism.',
  'Sooner or later it will be found that nothing really new happens in history. There could be talk of something really novel only if the unimaginable happened: if reason, humanity and love won a lasting victory.',
  'The idea wants changelessness and eternity. Whoever lives under the supremacy of the idea strives for permanence; hence everything that pushes towards change must be opposed to the idea.',
  'Not nature but the \“genius of mankind\” has knotted the hangman’s noose with which it can execute itself at any moment.',
  'Resistance to the organized mass can be effected only by the man who is as well organized in his individuality as the mass itself.',
  'If only a world-wide consciousness could arise that all division and all fission are due to the splitting of opposites in the psyche, then we should know where to begin.',
  'Masses are always breeding grounds of psychic epidemics.',
  'If a man is capable of leading a responsible life himself, then he is also conscious of his duties to the community.',
  'A million zeros joined together do not, unfortunately, add up to one.',
  'The heaping together of paintings by Old Masters in museums is a catastrophe; likewise, a collection of a hundred Great Brains makes one big fathead.',
  'Our blight is ideologies—they are the long-expected Antichrist!',
  'What depths of despair are still needed to open the eyes of the world’s responsible leaders, so that at least they can refrain from leading themselves into temptation?',
  'The principal and indeed the only thing that is wrong with the world is man.',
  'Knowledge rests not upon truth alone, but on error also.',
  'Mistakes are, after all, the foundations of truth, and if a man does not know what a thing is, it is at least an increase in knowledge if he knows what it is not.',
  'I do not call the man who admits his ignorance an obscurantist; I think it is much rather the man whose consciousness is not sufficiently developed to be aware of his ignorance.',
  'I do not take kindly to the argument that because certain working hypotheses may not possess eternal validity or may possibly be erroneous, they must be withheld from the public.',
  'Ultimate truth, if there be such a thing, demands the concert of many voices.',
  'Every victory contains the germ of future defeat.',
  'Nothing is more vulnerable and ephemeral than scientific theories, which are mere tools and not everlasting truths.'
  'We have to learn to think in antinomies, constantly bearing in mind that every truth turns into an antinomy if that is thought out to the end.',
  'I do not regard the pursuit of science as a bickering about who is right, but as an endeavor to augment and deepen human knowledge.',
  'It should not be forgotten that science is not the summa of life, that it is actually only one of the psychological attitudes, only one of the forms of human thought.',
  'Never do human beings speculate more, or have more opinions, than about things which they do not understand.',
  'Doubt alone is the mother of scientific truth. Whoever fights against dogma in high places falls victim, tragically enough, to the tyranny of a partial truth.',
  'Anyone who belittles the merits of Western science is undermining the foundations of the Western mind.',
  'A sign is always less than the thing it points to, and a symbol is always more than we can understand at first sight. Therefore we never stop at the sign but go on to the goal it indicates; but we remain with the symbol because it promises more than it reveals.',
  'Fantasy is not a sickness but a natural and vital activity which helps the seeds of psychic development to grow.',
  'Often the hands know how to solve a riddle with which the intellect has wrestled in vain.',
  'Concepts are coined and negotiable values; images are life.',
  'The true genius nearly always intrudes and disturbs. He speaks to a temporal world out of a world eternal. He says the wrong things at the right time.',
  'Being essentially the instrument of his work, [the artist] is subordinate to it, and we have no right to expect him to interpret it for us. He has done his utmost by giving it form, and must leave the interpretation to others and to the future.',
  'Only the mystics bring creativity into religion.',
  'Nothing is so jealous as truth.'
]



'Nothing is more vulnerable and ephemeral than scientific theories, which are mere tools and not everlasting truths.'
'We have to learn to think in antinomies, constantly bearing in mind that every truth turns into an antinomy if that is thought out to the end.',
'I do not regard the pursuit of science as a bickering about who is right, but as an endeavor to augment and deepen human knowledge.',
'It should not be forgotten that science is not the summa of life, that it is actually only one of the psychological attitudes, only one of the forms of human thought.',
'Never do human beings speculate more, or have more opinions, than about things which they do not understand.',
'Doubt alone is the mother of scientific truth. Whoever fights against dogma in high places falls victim, tragically enough, to the tyranny of a partial truth.',
'Anyone who belittles the merits of Western science is undermining the foundations of the Western mind.',
'A sign is always less than the thing it points to, and a symbol is always more than we can understand at first sight. Therefore we never stop at the sign but go on to the goal it indicates; but we remain with the symbol because it promises more than it reveals.',
'Fantasy is not a sickness but a natural and vital activity which helps the seeds of psychic development to grow.',
'Often the hands know how to solve a riddle with which the intellect has wrestled in vain.',
'Concepts are coined and negotiable values; images are life.',
'The true genius nearly always intrudes and disturbs. He speaks to a temporal world out of a world eternal. He says the wrong things at the right time.',
'Being essentially the instrument of his work, [the artist] is subordinate to it, and we have no right to expect him to interpret it for us. He has done his utmost by giving it form, and must leave the interpretation to others and to the future.',
'Only the mystics bring creativity into religion.',
'Nothing is so jealous as truth.'


'Error is just as important a condition of life’s progress as truth.',
'A fact never exists only as it is in itself, but also as we see it.',
'Human reality is made up of a thousand vulgarities.',
'Often it is just as well that we do not know the danger we escape when we rush in where angels fear to tread.',
'Emotion is not an activity of the individual but something that happens to him.',
'Naturally, you can make a wrong use of self-knowledge, just as of any other knowledge.',
'If only people could realize what an enrichment it is to find one’s own guilt, what a sense of honor and spiritual dignity!',
'The healthy man does not torture others—generally it is the tortured who turn into torturers.',
'If one does not understand a person, one tends to regard him as a fool.',
'Everyone who becomes conscious of even a fraction of his unconsciousness gets outside his own time and social stratum into a kind of solitude.',
'Our unwillingness to see our own faults and the projections of them onto others is the source of most quarrels, and the strongest guarantee that injustice, animosity, and persecution will not easily die out.',
'A man\'s hatred is always concentrated on the thing that makes him conscious of his bad qualities.',
'You always become the thing you fight the most.',
'Projections change the world into the replica of one\'s own unknown face.',
'How can anyone see straight when he does not even see himself and the darkness he unconsciously carries with him into all his dealings?',
'The \"other\" in us always seems alien and unacceptable; but if we let ourselves be aggrieved the feeling sinks in, and we are the richer for this little bit of self-knowledge.',
'Only a fool is interested in other people’s guilt, since he cannot alter it. The wise man learns only from his own guilt. He will ask himself: Who am I that all this should happen to me? To find the answer to this fateful question he will look into his own heart.',
'To know where the other person makes a mistake is of little value. It only becomes interesting when you know where you make the mistake, for then you can do something about it.',
'Self-knowledge, in the form of an examination of conscience, is demanded by Christian ethics. They were very pious people who maintained that self-knowledge paves the way to knowledge of God.',
'The foremost of all illusions is that anything can ever satisfy anybody. That illusion stands behind all that is unendurable in life and in front of all progress, and it is one of the most difficult things to overcome.',
'Let man but accumulate sufficient engines of destruction and the devil within him will soon be unable to resist putting them to their fated use. It is well known that fire-arms go off of themselves if only enough of them are together.',
'The persona is a complicated system of relations between individual consciousness and society, fittingly enough a kind of mask, designed on the one hand to make a definite impression upon others, and, on the other, to conceal the true nature of the individual.'
